[package]
name = "cgmath-geometry"
version = "0.1.0"
authors = ["Osspial <osspial@gmail.com>"]

[dependencies]
cgmath = { git = "https://github.com/Osspial/cgmath.git", branch = "prs_merged" }
num-traits = "0.1"
